###* GET ENTRY POINT
GET http://localhost:1515/

###* GET - Get all books
GET http://localhost:1515/books/

###* GET - Get book by ID
GET http://localhost:1515/books/5


###* GET - Get grouped books
GET http://localhost:1515/books/grouped

###* GET - Get book by title
GET http://localhost:1515/authors




###* POST - Create new Book
POST http://localhost:1515/books/
Content-Type: application/json

{
     "title": "AAAAA",
     "author_id": "fdads",
     "published_year": 2003
}

###* PUT - Update book by ID
PUT http://localhost:1515/books/3
Content-Type: application/json

{
     "title": "Dogs of Peace",
     "author_id": "OL14706704A",
     "published_year": 1928
}


###* DELETE - Delete book by ID
DELETE http://localhost:1515/books/3


