###* GET ----------------------------------------------------
###* GET ENTRY POINT
GET http://localhost:1515/

###* GET - Get all books
GET http://localhost:1515/books/

###* GET - Get all books with autor data

GET http://localhost:1515/books/authors_data

###* GET - Get book by ID
GET http://localhost:1515/books/2


###* GET - Get grouped books
GET http://localhost:1515/books/grouped

###* GET - Get book by title
GET http://localhost:1515/authors





###* POST ----------------------------------------------------
###* POST - Create new Book
POST http://localhost:1515/books/
Content-Type: application/json

{
     "title": "Book #3",
     "author_id": "PO",
     "published_year": 2003
}


###* PUT  ----------------------------------------------------
###* PUT - Update book by ID
PUT http://localhost:1515/books/3
Content-Type: application/json

{
     "title": "Dogs of Peace",
     "author_id": "OL14706704A",
     "published_year": 1928
}



###* DELETE ----------------------------------------------------
###* DELETE - Delete book by ID
DELETE http://localhost:1515/books/3


